<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * HomepageSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomepageSettingsRepository extends EntityRepository
{

    public function findSettings()
    {

            $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT s FROM AppBundle:HomepageSettings s '
                );

            $result = $query->getOneOrNullResult();


        return $result;
    }
}
