<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    public function findByIdWithCategories($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
              'SELECT p,c FROM AppBundle:Product p
               LEFT JOIN p.categories c
               WHERE
                p.id = :id
              '
            )
            ->setParameter('id',$id);
        $result = $query->getOneOrNullResult();

        return $result;
    }

    public function findByName($productName)
    {
        if(empty($productName))
        {
            $result = '';
        }
        else
        {
            $query = $this->getEntityManager()
                ->createQuery(
                    'SELECT p FROM AppBundle:Product p WHERE p.name LIKE :productName'
                )
                ->setParameter('productName','%'.$productName.'%');

            $result = $query->getResult();
        }

        return $result;
    }


    public function findAllWithCategoryBrand()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT c,p,b FROM AppBundle:Product p
                 LEFT JOIN p.categories c
                 LEFT JOIN p.brand b
                '
            );

        $result = $query->getResult();
        return $result;
    }

    public function findById($id)
    {

        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Product p
                 WHERE
                 p.id = :id
                '
            )
            ->setParameter('id',$id)
            ->getOneOrNullResult();
    }

}
